steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-loadconsumption/api:latest',
    '-f',
    'dockerfiles/api.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-loadconsumption/api:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - DOCKER_BUILDKIT=1
